### PR TITLE
Rename from Environment to Branch

### PR DESCRIPTION
**Pull request by alexon1234**
## Description

Rename the term `Environment` to `Branch`

### CODE REVIEW

**Comment by alrocar** [comment]
Let's wait a bit to merge this because I have an ongoing PR and maybe I can include it there

**Comment by xavijam** [comment]
I'm redoing the CI/CD guide and I realized we should do this. Could we do it now?

**Comment by xavijam** [comment]
Could you take a look @alexon1234 to my last changes 🙏 ?

**Comment by alexon1234** [comment]
> Could you take a look @alexon1234 to my last changes 🙏 ?

Looks fine, but @alrocar wanted to merge some changes. So let's wait until he finish his changes

**Comment by jlmadurga** [comment]
> > Could you take a look @alexon1234 to my last changes 🙏 ?
> 
> Looks fine, but @alrocar wanted to merge some changes. So let's wait until he finish his changes

I think it was already merged

**Comment by alexon1234** [comment]
BTW I can not approve my own PR cc/ @xavijam @jlmadurga

**Review by jlmadurga — APPROVED** [review]

**Pull request merged**
